spring:
  datasource:
    url: jdbc:postgresql://mateuspostgres.postgres.database.azure.com:5432/mateus-apps-database?user=mateusadmin&password=Mm130691&sslmode=require
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
