spring:
  datasource:
    url: jdbc:postgresql://mateuspostgres.postgres.database.azure.com:5432/mateus-apps-database?user=mateusadmin&password=Mm130691&sslmode=require
    username: mateusadmin
    password: Mm130691
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update