spring:
  datasource:
    url: jdbc:sqlserver://mateusappdb.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
